### ISSUE TITLE
Example app-npm doesn't work

### ISSUE THREAD

**Issue by Mavrin** [elidoran/cosmos-browserify#35]
when I try run example, I get following error 

```
While processing files with cosmos:browserify (for target web.browser):
client/lib/app.browserify.js: Cannot find module 'upper-case' from '.'
```

**Comment by elidoran** [comment]
Please provide more information so I can replicate the issue. Which Operating System? Which version of Node and Npm? Is the upper-case module in the node_modules folder in the root of the app? Did you run the command from the root of the app, or somewhere else?

I ask because when I do these commands on my systems it works for me:

```
git clone git@github.com:elidoran/cosmos-browserify-example.git
cd cosmos-browserify-example/app-npm
meteor run
```

**Comment by Mavrin** [comment]
I use Windows 7.
I use node version 5.3.0, npm version 3.3.12. 
But I try on  npm version 2._._. It doesn't work too.  
![image](https://cloud.githubusercontent.com/assets/1193817/11955542/dafc21e0-a8c3-11e5-93c3-c916963c5c41.png)

**Comment by elidoran** [comment]
Fixed with 0.9.3. I changed the basedir to an absolute path for Browserify and it's happy.

Also, I added an error message which will help with errors.

It works on Win7 with Node 5.3 and Npm 3.5.2

**Comment by Mavrin** [comment]
Now it works nice.
Thank you for quick fix.
