### ISSUE TITLE
after upgrading to meteor 1.5.2.1 from 1.5 get error

### ISSUE THREAD

**Issue by dpatte** [elidoran/cosmos-browserify#51]
While loading plugin `CosmosBrowserify` from package `cosmos:browserify`:
   module.js:325:15: Cannot find module 'emitter'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (/home/dpatte/sisi/node_modules/stream/index.js:22:15)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Module.Mp.load (/tools/tool-env/install-runtime.js:30:27)
   at Module.Mp.load
   (/home/dpatte/.meteor/packages/templating/.1.2.14.1m8jig9++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.require (/tools/isobuild/bundler.js:1900:22)
   at packages/CosmosBrowserify/plugin/browserify.coffee:10:14
   at packages/CosmosBrowserify/plugin/browserify.coffee:1:1
   at packages/CosmosBrowserify/plugin/browserify.coffee:1:1

I am not adding your module directly, but can't determine what is causing this error when I run. It didn't appear before upgrading to 1.5.2.1 from 1.5.

I have upgraded several apps with similar plugin atmosphere modules, but this error only occurs on one app.
